#pragma once
// Generated by `libxr gen`; do not edit by hand.
// MCU: STM32F103RCT6

#include "main.h"

#include "stm32_flash.hpp"

constexpr LibXR::FlashRegion FLASH_REGIONS[] = {
  {0x08000000, 0x00000800, 128},
};

constexpr size_t FLASH_REGION_NUMBER = sizeof(FLASH_REGIONS) / sizeof(LibXR::FlashRegion);