generator: 6.0.0
terminal_source: usb_fs_cdc
software_timer:
  priority: 2
  stack_depth: 1024
SPI:
  spi1:
    tx_buffer_size: 32
    rx_buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 3
I2C:
  i2c1:
    buffer_size: 32
    dma_section: ''
    dma_enable_min_size: 3
USART:
  usart1:
    tx_buffer_size: 128
    rx_buffer_size: 128
    dma_section: ''
    tx_queue_size: 5
ADC:
  adc1:
    buffer_size: 32
    dma_section: ''
    vref: 3.3
USB:
  usb_fs:
    enable: true
    ep0_packet_size: 8
    tx_buffer_size: 128
    rx_buffer_size: 128
    rx_fifo_size: 128
    tx_fifo_size: 128
    dma_section: ''
    cdc:
    - {tx_fifo_size: 128, rx_fifo_size: 128, queue_size: 3}
    vid: 5840
    pid: 5266
    bcd: 256
    manufacturer: XRobot
    product: STM32 XRUSB USB CDC Demo
    serial: XRUSB-DEMO-
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
  run_as_thread: false
database:
  enable: false
  block_size: 1
SYSTEM: FreeRTOS
